//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neuroglia.Data.Properties
{

    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neuroglia.Data.Properties.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid username and/or password.
        /// </summary>
        internal static string error_account_invalidcredentials {
            get {
                return ResourceManager.GetString("error_account_invalidcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Optimistic concurrency failure, object has been modified.
        /// </summary>
        internal static string error_identity_concurrencyfailure {
            get {
                return ResourceManager.GetString("error_identity_concurrencyfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An unknown failure has occurred.
        /// </summary>
        internal static string error_identity_defaulterror {
            get {
                return ResourceManager.GetString("error_identity_defaulterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email &apos;{email}&apos; is already taken.
        /// </summary>
        internal static string error_identity_duplicateemail {
            get {
                return ResourceManager.GetString("error_identity_duplicateemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role name &apos;{role}&apos; is already taken.
        /// </summary>
        internal static string error_identity_duplicaterolename {
            get {
                return ResourceManager.GetString("error_identity_duplicaterolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name &apos;{userName}&apos; is already taken.
        /// </summary>
        internal static string error_identity_duplicateusername {
            get {
                return ResourceManager.GetString("error_identity_duplicateusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email &apos;{email}&apos; is invalid.
        /// </summary>
        internal static string error_identity_invalidemail {
            get {
                return ResourceManager.GetString("error_identity_invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Role name &apos;{role}&apos; is invalid.
        /// </summary>
        internal static string error_identity_invalidrolename {
            get {
                return ResourceManager.GetString("error_identity_invalidrolename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid token.
        /// </summary>
        internal static string error_identity_invalidtoken {
            get {
                return ResourceManager.GetString("error_identity_invalidtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User name &apos;{username}&apos; is invalid, it can only contain letters or digits.
        /// </summary>
        internal static string error_identity_invalidusername {
            get {
                return ResourceManager.GetString("error_identity_invalidusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A user with this login already exists.
        /// </summary>
        internal static string error_identity_loginalreadyassociated {
            get {
                return ResourceManager.GetString("error_identity_loginalreadyassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect password.
        /// </summary>
        internal static string error_identity_passwordmismatch {
            get {
                return ResourceManager.GetString("error_identity_passwordmismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must have at least one digit (&apos;0&apos;-&apos;9&apos;).
        /// </summary>
        internal static string error_identity_passwordrequiresdigit {
            get {
                return ResourceManager.GetString("error_identity_passwordrequiresdigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must have at least one lowercase (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        internal static string error_identity_passwordrequireslower {
            get {
                return ResourceManager.GetString("error_identity_passwordrequireslower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must have at least one non alphanumeric character.
        /// </summary>
        internal static string error_identity_passwordrequiresnonalphanumeric {
            get {
                return ResourceManager.GetString("error_identity_passwordrequiresnonalphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must use at least {amount} different characters.
        /// </summary>
        internal static string error_identity_passwordrequiresuniquechars {
            get {
                return ResourceManager.GetString("error_identity_passwordrequiresuniquechars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must have at least one uppercase (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        internal static string error_identity_passwordrequiresupper {
            get {
                return ResourceManager.GetString("error_identity_passwordrequiresupper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passwords must be at least {length} characters.
        /// </summary>
        internal static string error_identity_passwordtooshort {
            get {
                return ResourceManager.GetString("error_identity_passwordtooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recovery code redemption failed.
        /// </summary>
        internal static string error_identity_recoverycoderedemptionfailed {
            get {
                return ResourceManager.GetString("error_identity_recoverycoderedemptionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User already has a password set.
        /// </summary>
        internal static string error_identity_useralreadyhaspassword {
            get {
                return ResourceManager.GetString("error_identity_useralreadyhaspassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User already in role &apos;{role}&apos;.
        /// </summary>
        internal static string error_identity_useralreadyinrole {
            get {
                return ResourceManager.GetString("error_identity_useralreadyinrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lockout is not enabled for this user.
        /// </summary>
        internal static string error_identity_userlockoutnotenabled {
            get {
                return ResourceManager.GetString("error_identity_userlockoutnotenabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User is not in role &apos;{role}&apos;.
        /// </summary>
        internal static string error_identity_usernotinrole {
            get {
                return ResourceManager.GetString("error_identity_usernotinrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to start a new operator session on the till with id &apos;{tillId}&apos;: an active operator session already exists.
        /// </summary>
        internal static string exception_domain_activetilloperatorsessionfound {
            get {
                return ResourceManager.GetString("exception_domain_activetilloperatorsessionfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to start a new session on the till with id &apos;{tillId}&apos;: an active session already exists.
        /// </summary>
        internal static string exception_domain_activetillsessionfound {
            get {
                return ResourceManager.GetString("exception_domain_activetillsessionfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} cannot be a date in the future.
        /// </summary>
        internal static string exception_domain_argumentcannotbeadateinthefuture {
            get {
                return ResourceManager.GetString("exception_domain_argumentcannotbeadateinthefuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is an invalid address.
        /// </summary>
        internal static string exception_domain_argumentisinvalidaddress {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is not a valid two-letter ISO 3166 country code.
        /// </summary>
        internal static string exception_domain_argumentisinvalidcountrycode {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidcountrycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is not a valid email address.
        /// </summary>
        internal static string exception_domain_argumentisinvalidemail {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} &apos;{value}&apos; is not a valid ISO 4217 currency code.
        /// </summary>
        internal static string exception_domain_argumentisinvalidiso4217code {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidiso4217code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is not a valid ISO 639-1 language code.
        /// </summary>
        internal static string exception_domain_argumentisinvalidiso6391code {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidiso6391code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is an invalid phone number.
        /// </summary>
        internal static string exception_domain_argumentisinvalidphonenumber {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidphonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} &apos;{value}&apos; is not a valid international phone number prefix.
        /// </summary>
        internal static string exception_domain_argumentisinvalidphonenumberprefix {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidphonenumberprefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} &apos;{value}&apos; is not a valid time zone id.
        /// </summary>
        internal static string exception_domain_argumentisinvalidtimezoneid {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvalidtimezoneid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is not a valid uri.
        /// </summary>
        internal static string exception_domain_argumentisinvaliduri {
            get {
                return ResourceManager.GetString("exception_domain_argumentisinvaliduri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} &apos;{value}&apos; is not supported. Supported values: {values}.
        /// </summary>
        internal static string exception_domain_argumentisunsupportedvalue {
            get {
                return ResourceManager.GetString("exception_domain_argumentisunsupportedvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be superior or equal to {min} and inferior or equal to {max}.
        /// </summary>
        internal static string exception_domain_argumentmustbecomprisedbetweenincluding {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbecomprisedbetweenincluding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be a time equal to or earlier than &apos;{time}&apos;.
        /// </summary>
        internal static string exception_domain_argumentmustbeearlierthan {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbeearlierthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be superior or equal to {quantity}.
        /// </summary>
        internal static string exception_domain_argumentmustbehigherorequalto {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbehigherorequalto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be higher or lower than {value}.
        /// </summary>
        internal static string exception_domain_argumentmustbehigherorlowerthan {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbehigherorlowerthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be higher than {min}.
        /// </summary>
        internal static string exception_domain_argumentmustbehigherthan {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbehigherthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be a time equal to or later than &apos;{time}&apos;.
        /// </summary>
        internal static string exception_domain_argumentmustbelaterthan {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbelaterthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be lower or equal to {quantity}.
        /// </summary>
        internal static string exception_domain_argumentmustbelowerorequalto {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbelowerorequalto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must be higher or equal to {quantity}.
        /// </summary>
        internal static string exception_domain_argumentmustbelowerorhigherthan {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbelowerorhigherthan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must contain digits only.
        /// </summary>
        internal static string exception_domain_argumentmustbenumeric {
            get {
                return ResourceManager.GetString("exception_domain_argumentmustbenumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must have a maximum length of {length}.
        /// </summary>
        internal static string exception_domain_argumentmusthavemaximumlengthof {
            get {
                return ResourceManager.GetString("exception_domain_argumentmusthavemaximumlengthof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument must have a minimum length of {length}.
        /// </summary>
        internal static string exception_domain_argumentmusthaveminimumlengthof {
            get {
                return ResourceManager.GetString("exception_domain_argumentmusthaveminimumlengthof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument cannot be null.
        /// </summary>
        internal static string exception_domain_argumentnull {
            get {
                return ResourceManager.GetString("exception_domain_argumentnull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {argument} argument cannot be null or empty.
        /// </summary>
        internal static string exception_domain_argumentnullorwhitespace {
            get {
                return ResourceManager.GetString("exception_domain_argumentnullorwhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The specified {argument} value &apos;{value}&apos; is out of range.
        /// </summary>
        internal static string exception_domain_argumentoutofrange {
            get {
                return ResourceManager.GetString("exception_domain_argumentoutofrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting entities of type &apos;{type}&apos; is not supported.
        /// </summary>
        internal static string exception_domain_deletionnotsupported {
            get {
                return ResourceManager.GetString("exception_domain_deletionnotsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A {entityType} with the specified {keyProperty} &apos;{key}&apos; already exists.
        /// </summary>
        internal static string exception_domain_entityalreadyexists {
            get {
                return ResourceManager.GetString("exception_domain_entityalreadyexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A {entityType} with the specified {keyProperties} already exists.
        /// </summary>
        internal static string exception_domain_entityalreadyexists_many {
            get {
                return ResourceManager.GetString("exception_domain_entityalreadyexists_many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtering is not allowed for the specified type &apos;{type}&apos;.
        /// </summary>
        internal static string exception_domain_filteringnotallowed {
            get {
                return ResourceManager.GetString("exception_domain_filteringnotallowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to cast the type &apos;{from}&apos; to the type &apos;{to}&apos;.
        /// </summary>
        internal static string exception_domain_invalidcast {
            get {
                return ResourceManager.GetString("exception_domain_invalidcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find the property &apos;{property}&apos; in the specified type &apos;{type}&apos;.
        /// </summary>
        internal static string exception_domain_missingproperty {
            get {
                return ResourceManager.GetString("exception_domain_missingproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The supplied {type} value &apos;{value}&apos; is not supported.
        /// </summary>
        internal static string exception_domain_notsupported {
            get {
                return ResourceManager.GetString("exception_domain_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find a &apos;{type}&apos; with the specified {keyProperty} &apos;{key}&apos;.
        /// </summary>
        internal static string exception_domain_nullreference {
            get {
                return ResourceManager.GetString("exception_domain_nullreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to find a &apos;{type}&apos; with the specified keys: {keys}.
        /// </summary>
        internal static string exception_domain_nullreference_many {
            get {
                return ResourceManager.GetString("exception_domain_nullreference_many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The {entityType} with {keyProperty} &apos;{key}&apos; is in an unexpected state &apos;{state}&apos;.
        /// </summary>
        internal static string exception_domain_unexpectedstate {
            get {
                return ResourceManager.GetString("exception_domain_unexpectedstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The entity of type &apos;{type}&apos; with {keyProperty} &apos;{id}&apos; has an unexpected &apos;{property}&apos; value &apos;{value}&apos;.
        /// </summary>
        internal static string exception_domain_unexpectedvalue {
            get {
                return ResourceManager.GetString("exception_domain_unexpectedvalue", resourceCulture);
            }
        }
    }
}
