name: Manual publish of .NET packages

on:
  workflow_dispatch:

env:
  SOLUTION: ./Neuroglia Framework.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Pull latest version tag
        if: github.event_name != 'pull_request'
        run: |
          git fetch
          git pull
      - name: Setup target .NET frameworks
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION }}" --configuration Release --no-restore
      
      - name: Publish NuGet Packages
        run: dotnet nuget push "./src/*/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
