name: Build .NET

on:
  workflow_call:

env:
  SOLUTION: ./Neuroglia Framework.sln

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Pull latest version tag
        if: github.event_name != 'pull_request'
        run: |
          git fetch
          git pull

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION }}" --configuration Release --no-restore
      
      - name: Cache build items
        if: github.event_name != 'pull_request'
        uses: actions/cache@v3
        id: build-dotnet-cache
        with:
          path: ./**/Release/*.nupkg
          key: build-dotnet-cache-${{ github.sha }}
