name: Build JS package

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        with:
          path: ${{ format('{0}{1}/', inputs.path, 'node_modules') }}
          key: ${{ inputs.name }}-node_modules

      - name: Restore build artifacts
        uses: actions/cache/restore@v3
        with:
          path: ${{ format('{0}{1}/', inputs.path, 'dist') }}
          key: ${{ inputs.name }}-dist
      
      - name: Build
        run: |
          cd ${{ inputs.path }}
          npx ng b ${{ inputs.name }} --configuration=production

      - name: Save build artifacts
        uses: actions/cache/save@v3
        with:
          path: ${{ format('{0}{1}/', inputs.path, 'dist') }}
          key: ${{ inputs.name }}-dist